name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
  
    name: "Sylius PHP - ${{ matrix.php }}-${{ matrix.distro }}"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
          php: ["7.4", "8.0"]
          distro: ['alpine']
          
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg PHP_VERSION=${{ matrix.php }} --tag piotrkardasz/sylius-php:${{ matrix.php }}-${{ matrix.distro }}
